project_id = "tcgkwxfmukljpaaafdwo"

[functions.generate-candidat-pdf]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.verify-reset-token]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.notify-registration]
verify_jwt = false

[functions.admin-update-password]
verify_jwt = false
